name: Build Documentation

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
  pull_request:
    branches: [main]
    paths:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: docs

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build documentation site
        run: bun run build
